apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qgraph.fullname" . }}-qgraph
  labels:
    {{- include "qgraph.labels" . | nindent 4 }}
    service-type: webserver
spec:
  selector:
    matchLabels:
      {{- include "qgraph.selectorLabels" . | nindent 6 }}
      service-type: webserver
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qgraph.selectorLabels" . | nindent 8 }}
        service-type: webserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-qgraph
          envFrom:
            - configMapRef:
                name: {{ include "qgraph.fullname" . }}-env-configmap
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.qgraph.repository }}:{{ .Values.qgraph.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.qgraph.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.qgraph.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.qgraph.resources | nindent 12 }}
