apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "name-lookup.fullname" . }}-solr-dep
  labels:
    {{- include "name-lookup.labels" . | nindent 4 }}
    app-name: solr
spec:
  serviceName: {{ include "name-lookup.fullname" . }}-solr-svc
  selector:
    matchLabels:
      {{- include "name-lookup.selectorLabels" . | nindent 6 }}
      app-name: solr
  template:
    metadata:
      labels:
        {{- include "name-lookup.selectorLabels" . | nindent 8 }}
        app-name: solr
    spec:
      volumes:
        - name: {{ include "name-lookup.fullname" . }}-configmap
          configMap:
            name: {{ include "name-lookup.fullname" . }}-configmap
            defaultMode: 0777
      {{ if .Values.dataUrl }}
      initContainers:
        - name: {{ .Chart.Name }}-download-backup
          image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
          command:
            - /download.sh
          volumeMounts:
            - mountPath: /var/solr/data
              name: {{ include "name-lookup.fullname" . }}-solr-data-vol
            - mountPath: "/download.sh"
              name: {{ include "name-lookup.fullname" . }}-configmap
              subPath: download.sh
          resources:
            {{- toYaml .Values.solr.initresources | nindent 12 }}
      {{ end }}
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}"
          args:
          - '-DzkRun'
          - '-q'
          - '-Dlog4j2.disable.jmx=true'
          - '-Dlog4j2.formatMsgNoLookups=true'
          env:
            - name: SOLR_JAVA_MEM
              value: "{{ .Values.solr.heap_mem }}"
            - name: SOLR_HOST
              value: {{ include "name-lookup.fullname" . }}-solr-svc
            - name: GC_TUNE
              value: {{ .Values.solr.gc | quote }}
              # "-XX:-UseLargePages -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=30 -XX:G1NewSizePercent=5 -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=70"
              # "-XX:-UseLargePages -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=20 -XX:G1NewSizePercent=5 -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=20"
              # "-XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=40 -XX:G1NewSizePercent=5 -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=90"
              # "-XX:NewSize=4G -XX:MaxNewSize=4G -XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=40 -XX:G1NewSizePercent=5 -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=90
          ports:
            - name: solr-port
              containerPort: {{ .Values.solr.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.solr.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/solr/data
              name: {{ include "name-lookup.fullname" . }}-solr-data-vol
      {{- with .Values.solr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.solr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.solr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "name-lookup.fullname" . }}-solr-data-vol
      spec:
        accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
