apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "name-lookup.fullname" . }}-solr-dep
  labels:
    {{- include "name-lookup.labels" . | nindent 4 }}
    app-name: solr
spec:
  serviceName: {{ include "name-lookup.fullname" . }}-solr-svc
  selector:
    matchLabels:
      {{- include "name-lookup.selectorLabels" . | nindent 6 }}
      app-name: solr
  template:
    metadata:
      labels:
        {{- include "name-lookup.selectorLabels" . | nindent 8 }}
        app-name: solr
    spec:
      volumes:
        - name: {{ include "name-lookup.fullname" . }}-configmap
          configMap:
            name: {{ include "name-lookup.fullname" . }}-configmap
            defaultMode: 0777
      {{ if .Values.dataUrl }}
      initContainers:
        - name: {{ .Chart.Name }}-download-backup
          image: busybox
          command:
            - /download.sh
          volumeMounts:
            - mountPath: /var/solr/data
              name: {{ include "name-lookup.fullname" . }}-solr-data-vol
            - mountPath: "/download.sh"
              name: {{ include "name-lookup.fullname" . }}-configmap
              subPath: download.sh
          resources:
            {{- toYaml .Values.solr.resources | nindent 12 }}

      {{ end }}
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}"
          args:
          - '-DzkRun'
          - '-q'
          - '-Dlog4j2.disable.jmx=true'
          - '-Dlog4j2.formatMsgNoLookups=true'
          env:
            - name: SOLR_JAVA_MEM
              value: "{{ .Values.solr.heap_mem }}"
            - name: SOLR_HOST
              value: {{ include "name-lookup.fullname" . }}-solr-svc
          ports:
            - name: solr-port
              containerPort: {{ .Values.solr.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.solr.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/solr/data
              name: {{ include "name-lookup.fullname" . }}-solr-data-vol

  volumeClaimTemplates:
    - metadata:
        name: {{ include "name-lookup.fullname" . }}-solr-data-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
