dataUrl: https://stars.renci.org/var/plater/bl-3.5.4/Reactome_Automat/d7df62d3266ae128/graph_d7df62d3266ae128.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.5.4/Reactome_Automat/d7df62d3266ae128/Reactome_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.5.4/Reactome_Automat/d7df62d3266ae128/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.5.4/Reactome_Automat/d7df62d3266ae128/testing_data.json