dataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/0e262e752794616a/graph_0e262e752794616a.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/0e262e752794616a/GtoPdb_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/0e262e752794616a/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/0e262e752794616a/sri_testing_data.json