plater:
  image: "ghcr.io/translatorsri/plater-clustered"
  version: "v1.6.3"
neo4j:
  image: "renciorg/neo4j-4.4.10-apoc-gds"
  version: "0.0.1"
busybox:
  image: "busybox"
  version: "1.35"
bash:
  image: "bash"
  version: "5.2.15"
