dataUrl: https://stars.renci.org/var/plater/bl-3.5.4/BINDING_Automat/711f33bcebbef313/graph_711f33bcebbef313.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.5.4/BINDING_Automat/711f33bcebbef313/BINDING_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.5.4/BINDING_Automat/711f33bcebbef313/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.5.4/BINDING_Automat/711f33bcebbef313/testing_data.json