dataUrl: https://stars.renci.org/var/plater/bl-3.2.1/HumanGOA_Automat/8d70f9e595173d0f/graph_8d70f9e595173d0f.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.2.1/HumanGOA_Automat/8d70f9e595173d0f/HumanGOA_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.2.1/HumanGOA_Automat/8d70f9e595173d0f/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.2.1/HumanGOA_Automat/8d70f9e595173d0f/sri_testing_data.json
